In [12]:
import pandas as pd
df = pd.read_csv('C:/Users/Admin/Downloads/transactions.csv')
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,8,CASH_OUT,158007.12,C424875646,0.00,0.00,C1298177219,474016.32,1618631.97,0
1,236,CASH_OUT,457948.30,C1342616552,0.00,0.00,C1323169990,2720411.37,3178359.67,0
2,37,CASH_IN,153602.99,C900876541,11160428.67,11314031.67,C608741097,3274930.56,3121327.56,0
3,331,CASH_OUT,49555.14,C177696810,10865.00,0.00,C462716348,0.00,49555.14,0
4,250,CASH_OUT,29648.02,C788941490,0.00,0.00,C1971700992,56933.09,86581.10,0

.
Creating more features from existing features including:
```
- How much money left the sender?
- Amount actually received.
- transaction size relative to account balance.
- whether accounts are depleted after the transaction

In [13]:
df['net_change_org'] = df['newbalanceOrig'] - df['oldbalanceOrg']
df['net_change_dest'] = df['newbalanceDest'] - df['oldbalanceDest']
df['ratio_amount_orig'] = df['amount'] / (df['oldbalanceOrg'] + 1e-5)
df['ratio_amount_dest'] = df['amount'] / (df['oldbalanceDest'] + 1e-5)
df['orig_zero_after'] = (df['newbalanceOrig'] == 0).astype(int)
df['dest_zero_after'] = (df['newbalanceDest'] == 0).astype(int)

In [14]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,net_change_org,net_change_dest,ratio_amount_orig,ratio_amount_dest,orig_zero_after,dest_zero_after
0,8,CASH_OUT,158007.12,C424875646,0.00,0.00,C1298177219,474016.32,1618631.97,0,0.0,1144615.65,1.580071e+10,3.333369e-01,1,0
1,236,CASH_OUT,457948.30,C1342616552,0.00,0.00,C1323169990,2720411.37,3178359.67,0,0.0,457948.30,4.579483e+10,1.683379e-01,1,0
2,37,CASH_IN,153602.99,C900876541,11160428.67,11314031.67,C608741097,3274930.56,3121327.56,0,153603.0,-153603.00,1.376318e-02,4.690267e-02,0,0
3,331,CASH_OUT,49555.14,C177696810,10865.00,0.00,C462716348,0.00,49555.14,0,-10865.0,49555.14,4.560988e+00,4.955514e+09,1,0
4,250,CASH_OUT,29648.02,C788941490,0.00,0.00,C1971700992,56933.09,86581.10,0,0.0,29648.01,2.964802e+09,5.207520e-01,1,0

```
Checking duplicate data...

In [15]:
print('Duplicates: ', df.duplicated().sum())

Duplicates:  0

```
Looking for missing values...

In [16]:
print('Missing values: ', df.isnull().sum())

Missing values:  step                 0
type                 0
amount               0
nameOrig             0
oldbalanceOrg        0
newbalanceOrig       0
nameDest             0
oldbalanceDest       0
newbalanceDest       0
isFraud              0
net_change_org       0
net_change_dest      0
ratio_amount_orig    0
ratio_amount_dest    0
orig_zero_after      0
dest_zero_after      0
dtype: int64

```
Changing data format...

In [19]:
df = df[df.select_dtypes(['int64', 'float64']).columns.tolist()].astype(int)

In [20]:
df.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,net_change_org,net_change_dest,ratio_amount_orig,ratio_amount_dest,orig_zero_after,dest_zero_after
0,8,158007,0,0,474016,1618631,0,0,1144615,15800711999,0,1,0
1,236,457948,0,0,2720411,3178359,0,0,457948,45794829999,0,1,0
2,37,153602,11160428,11314031,3274930,3121327,0,153603,-153603,0,0,0,0
3,331,49555,10865,0,0,49555,0,-10865,49555,4,4955514000,1,0
4,250,29648,0,0,56933,86581,0,0,29648,2964802000,0,1,0

```
Saving the new dataset...

In [21]:
df.to_csv('transactions_.csv', index=False)