*Dataset From Kaggle: https://www.kaggle.com/datasets/dhanushnarayananr/credit-card-fraud*

In today's course, we are going to learn data manipulation, or in other words, preparing data for Exploratory Data Analysis (EDA), 
where we will be discussing various topics, such as:
-
- grouping,
- appending,
- concatenating,
- merging,
- sorting,
- categorizing,
- removing duplicate data,
- dropping rows and columns,
- replacing data,
- changing data format, and finally,
- handling missing values.

In [1]:
import pandas as pd
data = pd.read_csv('C:/Users/Admin/Downloads/card_transdata.csv')
data.head(8)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
5,5.586408,13.261073,0.064768,1.0,0.0,0.0,0.0,0.0
6,3.724019,0.956838,0.278465,1.0,0.0,0.0,1.0,0.0
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0

In [2]:
print(data.shape)

(1000000, 8)


****Grouping****
-

In [3]:
#Grouping data serves the purpose of splitting a dataset into subsets based on one or more columns, then applying calculations
#to each group. It answers questions like: What is the average salary per department? How many customers per country? or What
#is the mean score for each class. And after grouping, we can aggregate the subsets using functions like mean(), sum(), count(), 
#min()/max(), and std.

grouped_data = data.groupby('repeat_retailer')['ratio_to_median_purchase_price'].mean()
print(grouped_data)
grouped_data = data.groupby('repeat_retailer')[['distance_from_home', 'distance_from_last_transaction']].mean()
print('\n',grouped_data)

repeat_retailer
0.0    1.813690
1.0    1.825592
Name: ratio_to_median_purchase_price, dtype: float64

                  distance_from_home  distance_from_last_transaction
repeat_retailer
0.0                        1.098464                        5.101957
1.0                       30.059650                        5.027726

****Appending****
-

In [4]:
#Appending means adding new rows to an existing dataset. For example, if our dataset contains 1,000,000 rows and 8 columns, and we
#want to add rows that are related to this dataset, our new dataset must contain exactly the same columns as the existing one. 
#In this case, the new dataset hasy 8 columns. However, when appending, the number of rows in the new dataset can vary.

data1 = pd.read_csv('C:/Users/Admin/Downloads/card_transdata.csv')
data2 = pd.read_csv('C:/Users/Admin/Downloads/card_transdata.csv')

print('data1 shape: ', data1.shape, '\ndata2 shape: ', data2.shape)

#To append data2 to data1, we will use pd.concat() function:

appended = pd.concat([data1, data2], axis=0)
print('Shape of the appended data: ', appended.shape)

#When appending, writing 'axis=0' is not mandatory, as it is default

data1 shape:  (1000000, 8)
data2 shape:  (1000000, 8)
Shape of the appended data:  (2000000, 8)

****Concatenating****
-

In [5]:
#Concatenating is similar to appending, but now instead of adding new rows, we can add new columns to an existing dataset by
#specifying 'axis=1'. See below:

concatenated = pd.concat([data1, data2], axis=1)
print('Shape of the concatenated data: ', concatenated.shape)

Shape of the concatenated data:  (1000000, 16)

****Merging****
-

In [6]:
#Merging means combing two datasets based on one or more common columns (keys). Unlike append/concat, which just stack data,
#merge aligns rows based on a key column. There are various types of merge: 1. Inner join keeps only rows with keys present
#in both datasets, 2. Left join keeps all rows from the left dataset, add matching rows from the right, 3. Right join keeps
#all rows from the right dataset, add matching rows from the left, 4. Outer join keeps all rows from both datasets, fill missing
#values with NaN. However, merging defaults to 'Inner join'.

data1 = pd.read_csv('C:/Users/Admin/Downloads/card_transdata_1.csv')
data2 = pd.read_csv('C:/Users/Admin/Downloads/card_transdata_2.csv')
print('Shape of data1: ', data1.shape)
print('Shape of data2: ', data2.shape)

#Inner Join
merged_inner = pd.merge(data1, data2, on='Customer ID', how='inner')
print('\nShape of merged (Inner join) data: ', merged_inner.shape)

#Left Join
merged_left = pd.merge(data1, data2, on='Customer ID', how='left')
print('Shape of merged (Left join) data: ', merged_left.shape)

#Right Join
merged_right = pd.merge(data1, data2, on='Customer ID', how='right')
print('Shape of merged (Right join) data: ', merged_right.shape)

#Outer Join
merged_outer = pd.merge(data1, data2, on='Customer ID', how='outer')
print('Shape of merged (Right join) data: ', merged_outer.shape)

#I just added a column called "Customer ID" manually. See below the datasets I used for merging.

Shape of data1:  (1000000, 9)
Shape of data2:  (1000000, 9)

Shape of merged (Inner join) data:  (500000, 17)
Shape of merged (Left join) data:  (1000000, 17)
Shape of merged (Right join) data:  (1000000, 17)
Shape of merged (Right join) data:  (1500000, 17)

In [7]:
data1.head(10)

,Customer ID,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,2,57.877857,0.311140,1.945940,1,1,0,0,0
1,4,10.829943,0.175592,1.294219,1,0,0,0,0
2,6,5.091079,0.805153,0.427715,1,0,0,1,0
3,8,2.247564,5.600044,0.362663,1,1,0,1,0
4,10,44.190936,0.566486,2.222767,1,1,0,1,0
5,12,5.586408,13.261073,0.064768,1,0,0,0,0
6,14,3.724019,0.956838,0.278465,1,0,0,1,0
7,16,4.848247,0.320735,1.273050,1,0,1,0,0
8,18,0.876632,2.503609,1.516999,0,0,0,0,0
9,20,8.839047,2.970512,2.361683,1,0,0,1,0

In [8]:
data2.head(10)

,Customer ID,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,1,10.829943,0.175592,1.294219,1,0,0,0,0
1,2,5.091079,0.805153,0.427715,1,0,0,1,0
2,3,2.247564,5.600044,0.362663,1,1,0,1,0
3,4,44.190936,0.566486,2.222767,1,1,0,1,0
4,5,5.586408,13.261073,0.064768,1,0,0,0,0
5,6,3.724019,0.956838,0.278465,1,0,0,1,0
6,7,4.848247,0.320735,1.273050,1,0,1,0,0
7,8,0.876632,2.503609,1.516999,0,0,0,0,0
8,9,57.877857,0.311140,1.945940,1,1,0,0,0
9,10,8.839047,2.970512,2.361683,1,0,0,1,0

****Sorting****
-

In [9]:
#Sorting means arranging the dataset in a specific order, either ascending (small to large) or descending (large to small). Sorting
#can be applied to one or multiple columns.

data = pd.read_csv('C:/Users/Admin/Downloads/card_transdata.csv')

#Sort by Ascending:
data_sorted = data.sort_values(by=['distance_from_home', 'ratio_to_median_purchase_price'], ascending=True)
data_sorted.head(8)

#If you use 'ascending=False', the selected column(s) with descending order. You can also specify the order for multiple columns 
#individually, e.g.,'Ascending=['True', False]' where the first column is sorted ascending and the second descending.

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
343092,0.004874,0.198102,0.998148,0.0,0.0,0.0,1.0,0.0
37805,0.021322,0.092965,1.630654,0.0,0.0,1.0,1.0,0.0
564282,0.022599,0.919819,1.074830,0.0,0.0,0.0,1.0,0.0
428372,0.024144,3.326575,0.730539,0.0,1.0,0.0,1.0,0.0
239205,0.024461,0.975814,0.187773,0.0,1.0,0.0,1.0,0.0
428129,0.024602,1.405366,1.446399,0.0,0.0,0.0,0.0,0.0
888520,0.025847,5.953238,4.342023,0.0,0.0,0.0,0.0,1.0
969655,0.026182,0.471677,0.591039,0.0,0.0,0.0,1.0,0.0

****Categorizing****
-

In [10]:
#Categorizing means converting data into categories or groups. It turns data into meaningful buckets or group, making analysis
#and ML easier. When we talk about categorizing data, we specifically refer to binning or cutting a dataset. Here, we will use
#pd.cut() to categorize our numeric data.

#Categorizing "distance_from_home"

import numpy as np
data['categorized_dfh'] = pd.cut(data['distance_from_home'], bins=[0, 500, 4500, np.inf], labels=['low', 'medium', 'high'])

data.head(15)

#The 'categorized_dfh' has been added to the last column, see the result:

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,categorized_dfh
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0,low
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0,low
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0,low
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0,low
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0,low
5,5.586408,13.261073,0.064768,1.0,0.0,0.0,0.0,0.0,low
6,3.724019,0.956838,0.278465,1.0,0.0,0.0,1.0,0.0,low
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0,low
8,0.876632,2.503609,1.516999,0.0,0.0,0.0,0.0,0.0,low
9,8.839047,2.970512,2.361683,1.0,0.0,0.0,1.0,0.0,low
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0,low
11,13.592368,0.240540,1.370330,1.0,1.0,0.0,1.0,0.0,low
12,765.282559,0.371562,0.551245,1.0,1.0,0.0,0.0,0.0,medium
13,2.131956,56.372401,6.358667,1.0,0.0,0.0,1.0,1.0,low
14,13.955972,0.271522,2.798901,1.0,0.0,0.0,1.0,0.0,low

In [11]:
#You can let pd.cut() function to calculate the bin ranges automatically, but in this case the widths of the ranges may differ, see below:

data['categorized_dfh'] = pd.cut(data['distance_from_home'], bins=3, labels=['low', 'medium', 'high'])
data.head(8)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,categorized_dfh
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0,low
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0,low
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0,low
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0,low
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0,low
5,5.586408,13.261073,0.064768,1.0,0.0,0.0,0.0,0.0,low
6,3.724019,0.956838,0.278465,1.0,0.0,0.0,1.0,0.0,low
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0,low

****Removing Duplicate Rows****
-

In [12]:
#Removing duplicate rows means removing rows that are exactly the same or have same values in specific columns. Duplicate data/rows can 
#inflate counts, bias analysis, and affect ML models. Removing duplicates ensures clean, accurate datasets.

#Let's check if any duplicate data exists:
print(data.duplicated().sum())

0

In [13]:
#In our current dataset, there are no duplicate rows. For demonstration purposes, I created the dataset below for learners. See below:

data_ = pd.read_csv('C:/Users/Admin/Downloads/Book 1(Sheet1).csv')
print(data_)

#See, there are two duplicate rows (Sam and Nikita).

         Name  Transaction_amount
0       David                 300
1         Sam                 760
2   Alexander                 354
3      Nikita                 593
4        Paul                 873
5      Joshua                 374
6      Barnum                 980
7         Sam                 760
8        Alex                 346
9       Farzi                 865
10     Nikita                 593
11   Lovelace                 675
12       Lucy                 456
13       Adam                 845

In [14]:
#Now let's check how many duplicate data/rows exist in our current dataset:

duplicate_rows = data_.duplicated()
print(duplicate_rows)
print('\nCount duplicated rows: ', duplicate_rows.sum())

#Let's remove the duplicate rows:
removed_dup = data_.drop_duplicates()
print('\n', removed_dup)
print('\nCount duplicated rows: ', removed_dup.duplicated().sum())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11    False
12    False
13    False
dtype: bool

Count duplicated rows:  2

          Name  Transaction_amount
0       David                 300
1         Sam                 760
2   Alexander                 354
3      Nikita                 593
4        Paul                 873
5      Joshua                 374
6      Barnum                 980
8        Alex                 346
9       Farzi                 865
11   Lovelace                 675
12       Lucy                 456
13       Adam                 845

Count duplicated rows:  0

****Dropping Rows and Columns****
-

In [23]:
#We can also drop specific rows and columns for any particular reason. For example, if there is a defecton data entry, we may 
#remove a specific row, or sometimes an entire column.

data = pd.read_csv('C:/Users/Admin/Downloads/card_transdata.csv')

print('Shape of the data: ', data.shape)

#Let's drop a random row (for demonstration only):

data = data.drop(labels=[3], axis=0)
print('Shape after dropping row_4: ', data.shape)

#Let's drop a column from our dataset:
data = data.drop(labels=['repeat_retailer'], axis=1)
print('Shape after dropping a column: ', data.shape)

Shape of the data:  (1000000, 8)
Shape after dropping row_4:  (999999, 8)
Shape after dropping a column:  (999999, 7)

****Replacing data****
-

In [27]:
#Replacing data refers to changing specific values in a dataset. Sometimes we need to convert a numeric column into categorical values,
#we can use replce() method for that purpose. It can also be used on a specific column if it contains inconsistent values.

data['replaced_fraud'] = data['fraud'].replace([0, 1], ['not_fraud', 'fraud'])
data.head(15)


#replaced_fraud has been added to the last column, see the result below:

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,used_chip,used_pin_number,online_order,fraud,replaced_fraud
0,57.877857,0.311140,1.945940,1.0,0.0,0.0,0.0,not_fraud
1,10.829943,0.175592,1.294219,0.0,0.0,0.0,0.0,not_fraud
2,5.091079,0.805153,0.427715,0.0,0.0,1.0,0.0,not_fraud
4,44.190936,0.566486,2.222767,1.0,0.0,1.0,0.0,not_fraud
5,5.586408,13.261073,0.064768,0.0,0.0,0.0,0.0,not_fraud
6,3.724019,0.956838,0.278465,0.0,0.0,1.0,0.0,not_fraud
7,4.848247,0.320735,1.273050,0.0,1.0,0.0,0.0,not_fraud
8,0.876632,2.503609,1.516999,0.0,0.0,0.0,0.0,not_fraud
9,8.839047,2.970512,2.361683,0.0,0.0,1.0,0.0,not_fraud
10,14.263530,0.158758,1.136102,1.0,0.0,1.0,0.0,not_fraud
11,13.592368,0.240540,1.370330,1.0,0.0,1.0,0.0,not_fraud
12,765.282559,0.371562,0.551245,1.0,0.0,0.0,0.0,not_fraud
13,2.131956,56.372401,6.358667,0.0,0.0,1.0,1.0,fraud
14,13.955972,0.271522,2.798901,0.0,0.0,1.0,0.0,not_fraud
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,0.0,not_fraud

****Changing data format****
-

In [30]:
#Changing data format means converting a column from one data type to another.

#For example, in our dataset, the Online orders are stored as float, datatype values, we can convert that to integer datatype values:

data['online_order_changed'] = data['online_order'].astype(int)
data.head()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,used_chip,used_pin_number,online_order,fraud,replaced_fraud,pin_number_changed,online_order_changed
0,57.877857,0.311140,1.945940,1.0,0.0,0.0,0.0,not_fraud,0,0
1,10.829943,0.175592,1.294219,0.0,0.0,0.0,0.0,not_fraud,0,0
2,5.091079,0.805153,0.427715,0.0,0.0,1.0,0.0,not_fraud,0,1
4,44.190936,0.566486,2.222767,1.0,0.0,1.0,0.0,not_fraud,0,1
5,5.586408,13.261073,0.064768,0.0,0.0,0.0,0.0,not_fraud,0,0

In [31]:
# Missing values are entries in a dataset that are empty, NaN, or null. We can use dropna() to remove rows with missing values,
# and fillna() to fill missing values with a constant (e.g., 0), the mean, or the mode of the column.

#Let's check if there are any missing values:
data.isnull().sum()

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
replaced_fraud                    0
pin_number_changed                0
online_order_changed              0
dtype: int64

In [32]:
# Since there are no missing values in our dataset, I am intentionally removing some values from multiple columns for educational 
#purposes:

data = pd.read_csv('C:/Users/Admin/Downloads/card_transdata(in).csv')
data.head(10)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,10.829943,0.175592,1.294219,1,0,0,0,0
1,5.091079,0.805153,0.427715,1,0,0,1,0
2,2.247564,5.600044,0.362663,1,1,0,1,0
3,NaN,0.566486,2.222767,1,1,0,1,0
4,5.586408,13.261073,NaN,1,0,0,0,0
5,3.724019,NaN,0.278465,1,0,0,1,0
6,4.848247,0.320735,1.273050,1,0,1,0,0
7,NaN,2.503609,1.516999,0,0,0,0,0
8,57.877857,0.311140,NaN,1,1,0,0,0
9,8.839047,2.970512,2.361683,1,0,0,1,0

In [33]:
#Let's check any missing value exist now:
data.isnull().sum()

distance_from_home                2
distance_from_last_transaction    1
ratio_to_median_purchase_price    2
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

In [34]:
# Now, let's drop the rows that contain any missing values:

data = data.dropna()
data.isnull().sum()

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

In [35]:
#Now our dataset contains no missing values.
data.head(10)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,10.829943,0.175592,1.294219,1,0,0,0,0
1,5.091079,0.805153,0.427715,1,0,0,1,0
2,2.247564,5.600044,0.362663,1,1,0,1,0
6,4.848247,0.320735,1.273050,1,0,1,0,0
9,8.839047,2.970512,2.361683,1,0,0,1,0
10,14.263530,0.158758,1.136102,1,1,0,1,0
11,13.592368,0.240540,1.370330,1,1,0,1,0
12,765.282559,0.371562,0.551245,1,1,0,0,0
13,2.131956,56.372401,6.358667,1,0,0,1,1
14,13.955972,0.271522,2.798901,1,0,0,1,0

In [38]:
#Let's dive into fillna():

# 1. Fill the empty cells with 0:
data = pd.read_csv('C:/Users/Admin/Downloads/card_transdata(in).csv')

data = data.fillna(0)

data.head(10)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,10.829943,0.175592,1.294219,1,0,0,0,0
1,5.091079,0.805153,0.427715,1,0,0,1,0
2,2.247564,5.600044,0.362663,1,1,0,1,0
3,0.000000,0.566486,2.222767,1,1,0,1,0
4,5.586408,13.261073,0.000000,1,0,0,0,0
5,3.724019,0.000000,0.278465,1,0,0,1,0
6,4.848247,0.320735,1.273050,1,0,1,0,0
7,0.000000,2.503609,1.516999,0,0,0,0,0
8,57.877857,0.311140,0.000000,1,1,0,0,0
9,8.839047,2.970512,2.361683,1,0,0,1,0

In [41]:
# 2.Fill the empty cells with mean()
data = pd.read_csv('C:/Users/Admin/Downloads/card_transdata(in).csv')

data['distance_from_home'] = data['distance_from_home'].fillna(data['distance_from_home'].mean())
data['distance_from_last_transaction'] = data['distance_from_last_transaction'].fillna(data['distance_from_last_transaction'].mean())
data['ratio_to_median_purchase_price'] = data['ratio_to_median_purchase_price'].fillna(data['ratio_to_median_purchase_price'].mean())

data.head(10)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,10.829943,0.175592,1.294219,1,0,0,0,0
1,5.091079,0.805153,0.427715,1,0,0,1,0
2,2.247564,5.600044,0.362663,1,1,0,1,0
3,26.628800,0.566486,2.222767,1,1,0,1,0
4,5.586408,13.261073,1.824184,1,0,0,0,0
5,3.724019,5.036523,0.278465,1,0,0,1,0
6,4.848247,0.320735,1.273050,1,0,1,0,0
7,26.628800,2.503609,1.516999,0,0,0,0,0
8,57.877857,0.311140,1.824184,1,1,0,0,0
9,8.839047,2.970512,2.361683,1,0,0,1,0

In [ ]:
# 3.Like, you can use mode() or.